Update subgraph.md
lidofinance/docs pull request #130
Opened 2022-08-29 12:35 UTC by PaulieB14

@kolysapphire.  Made changes and added subgraph info and links to existing subgraph file and also added query examples.

2022-08-29 16:34 UTC, PaulieB14 commented
@kolyasapphire I have 2 additional query examples - should I add?

2022-08-30 11:44 UTC, kolyasapphire commented
Examples are good now, should be enough, will request a few other changes

2022-08-30 11:44 UTC, kolyasapphire requested changes

2022-08-30 11:44 UTC, kolyasapphire commented on docs/integrations/subgraph.md
> +- Graphql Endpoint: https://gateway.thegraph.com/api/[api-key]/subgraphs/id/HXfMc1jPHfFQoccWd7VMv66km75FoxVHDMvsJj5vG5vf
GraphQL

2022-08-30 11:44 UTC, kolyasapphire commented on docs/integrations/subgraph.md
> +## Obtain keys of node operator
Node Operator Keys

2022-08-30 11:44 UTC, kolyasapphire commented on docs/integrations/subgraph.md
> +Query description: obtain keys of node operator
Fetch validator keys of a node operator.

2022-08-30 12:27 UTC, PaulieB14 commented on docs/integrations/subgraph.md
> +<br />
Did this just for spacing.  I can take them out.

2022-08-30 12:31 UTC, PaulieB14 commented
@kolyasapphire.  I revised and think we are good to go.  If you need any revisions let me know.  Also we are working on automation of getting schema into a markdown file with entities if you are interested using python code.  I know you didn't want entities displayed since so many but maybe if automated it would be easier when updates.

2022-08-30 12:41 UTC, kolyasapphire commented
Thanks, but yes, entity data automation not necessary at this time

2022-08-30 12:42 UTC, kolyasapphire commented
Last thing - please remove `.vscode/settings.json` and we're ready to go

2022-08-30 13:01 UTC, PaulieB14 commented
@kolyasapphire I believe it's changed now.   Please let me know

2022-08-30 13:03 UTC, kolyasapphire commented
Don't see the change

2022-08-30 13:23 UTC, PaulieB14 commented
@kolyasapphire  - should be deleted now

2022-08-30 13:45 UTC, kolyasapphire approved these changes

2022-08-30 13:46 UTC, kolyasapphire commented
All good now! Will merge and adjust wording a bit. Thanks a lot for your help!

2022-08-30 13:47 UTC, merged