LOL msig roations
lidofinance/docs pull request #311
Opened 2024-01-17 08:49 UTC by grstepanov

Update compositions of LOL multisigs on mainnet and L2s

2024-01-23 09:50 UTC, grstepanov commented
Forum thread post to check compositions against: https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-pool/5335/11

2024-01-24 17:57 UTC, JennyKop commented on docs/multisigs/committees.md
Let's add the link to the current forum topic here, instead of this one: [Proposal to move from LDO, DAI to stETH](https://research.lido.fi/t/lido-v2-may-1-2023-december-31-2023-lido-ongoing-grant-request/4476)
have [Liquidity Observation Lab (LOL): Liquidity Strategy and application to Curve stETH:ETH Pool](https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-pool/5335)

2024-01-24 18:17 UTC, JennyKop commented on docs/multisigs/committees.md
incorrect (Carvas was mixed up with adcv), need to be changed to 
| adcv | 0xcC692077C65dd464cAA7e7ae614328914f8469b3 | https://etherscan.io/verifySig/11698 | https://twitter.com/adcv_/status/1587404360476237829 |

2024-01-24 18:39 UTC, JennyKop requested changes
We should tweak two comments before merging. Everything else is fine, I've checked:
- that all multisigs are in place
- links, signatures, and addresses of signers match the announcement on the forum and the actual content in the safe

2024-01-25 07:58 UTC, grstepanov commented on docs/multisigs/committees.md
Makes sense, thx

2024-01-25 08:09 UTC, JennyKop approved these changes
Looks great to me

2024-01-25 08:14 UTC, merged