Doc: update guides
lidofinance/docs pull request #381
Opened 2024-07-02 22:49 UTC by TheDZhon

## Guide updates

### Update tokens integration guide
- [x] Update well-known integration references (include Mellow LRT)
- [x] Update token pricing approach
- [x] Update liquidity venues
- [x] Update risks
- [x] More L2 networks available

###  Update bridging guide
- [x] Exclude Lido contributors commitment from reviewing
- [x] Propose `state-mate`
- [x] Refer to Mode
- [x] Add Scroll case

2024-07-03 06:13 UTC, arwer13 requested changes

2024-07-03 06:13 UTC, arwer13 commented on docs/guides/lido-tokens-integration-guide.md
> +- stETH/wstETH is a very liquid token with billions of liquidity locked in liquidity pools (see [above](./lido-tokens-integration-guide.md#sttokens-steth-and-wsteth))
```suggestion
- stETH/wstETH is a very liquid token with billions of liquidity locked in liquidity pools (see [above](#sttokens-steth-and-wsteth))
```

2024-07-03 06:13 UTC, arwer13 commented on docs/guides/lido-tokens-integration-guide.md
> +- On AAVE v3, multiple tokens can be borrowed against wstETH on various chains (see the list of the [markets](./lido-tokens-integration-guide.md#sttokens-steth-and-wsteth))
```suggestion
- On AAVE v3, multiple tokens can be borrowed against wstETH on various chains (see the list of the [markets](#sttokens-steth-and-wsteth))
```

2024-07-03 08:42 UTC, TheDZhon commented
Thanks, @arwer13 
Applied all of the suggestions :+1:

2024-07-04 13:21 UTC, mymphe commented on docs/guides/lido-tokens-integration-guide.md
> +Normally, stETH rebases happen daily when the Lido oracle reports the Consensus Layer ether balance update. The rebase can be positive or negative, depending on the validators' performance. In case L
> slashed or penalized

Same thing?

2024-07-04 13:21 UTC, mymphe commented on docs/guides/lido-tokens-integration-guide.md
> +The accounting oracle has sanity checks on both max APR reported (the APR cannot exceed 27%, which means a daily rebase is limited to `27/365%`) and total staked amount drop (staked ether decrease re
`(27/365)%`

2024-07-04 13:21 UTC, mymphe commented on docs/guides/lido-tokens-integration-guide.md
> +Currently, the oracle report is based on five oracle daemons hosted by established node operators selected by the DAO. As soon as five out of nine oracle daemons report the same data, reaching the co
> report is based on five oracle daemons

It's based on nine, but at least five need to report, isn't it? Better rephrase completely, e.g.

Oracle network includes 9 oracles...

2024-07-04 13:21 UTC, mymphe commented on docs/guides/lido-tokens-integration-guide.md
> +Avoid storing cached stETH balance for extended periods of time (over 24 hours), and keep in mind it doesn't necessarily take a transaction to change stETH balance.
> it doesn't necessarily take a transaction to change stETH balance

It does take a transaction, though not the holder's but still haha

We can rephrase it to something like
"Note that stETH balance changes on each rebase without any incoming or outgoing user transfers and does not emit ERC-20 'Transfer' events"

2024-07-04 13:21 UTC, mymphe commented on docs/guides/lido-tokens-integration-guide.md
> +  There is an inherent risk that Lido could contain a smart contract vulnerability or bug. The Lido code is open-sourced, audited, and covered by an extensive bug bounty program to minimize this risk
> open-sourced

open-source

"Open-sourced" sounds like it was "sourced from the open"  🌚

2024-07-04 13:21 UTC, mymphe commented on docs/token-guides/wsteth-bridging-guide.md
> +To speed the process up, you might perform a deployment verification against the bytecode already used for another network and configuration/storage state comparison to be 1:1 except only for the net
> To speed the process up

To speed up the process

2024-07-04 18:08 UTC, TheDZhon commented on docs/guides/lido-tokens-integration-guide.md
> +Normally, stETH rebases happen daily when the Lido oracle reports the Consensus Layer ether balance update. The rebase can be positive or negative, depending on the validators' performance. In case L
nor really

2024-07-04 18:20 UTC, mymphe approved these changes

2024-07-05 13:10 UTC, merged