feat(deployed-addresses): add Mode Mainnet and Sepolia addresses
lidofinance/docs pull request #399
Opened 2024-07-30 19:32 UTC by arwer13

2024-07-30 19:47 UTC, TheDZhon requested changes
:eyes:

2024-07-30 19:47 UTC, TheDZhon commented on docs/deployed-contracts/index.md
I think that a new emergency msig is missing here :thinking:

2024-07-30 19:47 UTC, TheDZhon commented on docs/deployed-contracts/sepolia.md
> +- L1ERC20TokenBridge: [`0xD847780c8808fc99727001C43E6C17A198b39729`](https://sepolia.etherscan.io/address/0xD847780c8808fc99727001C43E6C17A198b39729) (proxy)
should be [0x16B929D35B200EA0ae0B93EABc3Bf9Ad611BF18F](https://sepolia.etherscan.io/address/0x16B929D35B200EA0ae0B93EABc3Bf9Ad611BF18F#readContract)

2024-07-30 19:47 UTC, TheDZhon commented on docs/deployed-contracts/sepolia.md
> +- L1ERC20TokenBridge: [`0x514Aa1d41d840af7572509D75354A8612594eB30`](https://sepolia.etherscan.io/address/0x514Aa1d41d840af7572509D75354A8612594eB30) (impl)
should be https://sepolia.etherscan.io/address/0x8c1E68A74E71594925c7D7a78Ef43657aec4d599

2024-07-30 19:47 UTC, TheDZhon commented on docs/deployed-contracts/sepolia.md
> +- WstETH ERC20Bridged: [`0x953757Db814392642e614DaBba794Ef4381D8292`](https://sepolia.explorer.mode.network/address/0x953757Db814392642e614DaBba794Ef4381D8292) (proxy)
should be [0x2C937931B5d544E3dff1d9D78c80d9772B55837A](https://sepolia.explorer.mode.network/address/0x2C937931B5d544E3dff1d9D78c80d9772B55837A)

2024-07-30 19:47 UTC, TheDZhon commented on docs/deployed-contracts/sepolia.md
> +- WstETH ERC20Bridged: [`0x9C7CDB9312ddA72ACc24E4A3bE5aA6afeca2AAFE`](https://sepolia.explorer.mode.network/address/0x9C7CDB9312ddA72ACc24E4A3bE5aA6afeca2AAFE) (impl)
should be https://sepolia.explorer.mode.network/address/0xC9C796E4CefdD38Eb462E84246bE41d500149162

2024-07-30 19:47 UTC, TheDZhon commented on docs/deployed-contracts/sepolia.md
> +- L2ERC20TokenBridge: [`0x2F3a332eff5f45cEA0486464fa4080fcF52Ea876`](https://sepolia.explorer.mode.network/address/0x2F3a332eff5f45cEA0486464fa4080fcF52Ea876) (proxy)
should be [0xd41a90e55bcfC1CbF96D78aE80BbCB56A6BA0008](https://sepolia.explorer.mode.network/address/0xd41a90e55bcfC1CbF96D78aE80BbCB56A6BA0008)

2024-07-30 19:47 UTC, TheDZhon commented on docs/deployed-contracts/sepolia.md
> +- L2ERC20TokenBridge: [`0x2AD850d0c6b1846F9bBD8144362A586330a96B31`](https://sepolia.explorer.mode.network/address/0x2AD850d0c6b1846F9bBD8144362A586330a96B31) (impl)
should be https://sepolia.explorer.mode.network/address/0x8Cc0183D53c8fB160BFB01fe49ff3E8A9Aa0B1F6

2024-07-31 11:56 UTC, TheDZhon requested changes
LGTM, but let's add the 'proposed' marks and resolve merge conflicts :pray:

2024-07-31 12:14 UTC, TheDZhon approved these changes
LGTM

2024-08-01 13:31 UTC, zuzueeka approved these changes

2024-08-01 13:40 UTC, merged