SR-1.5 updates
lidofinance/docs pull request #402
Opened 2024-08-08 21:26 UTC by krogla

2024-09-06 11:05 UTC, mkurayan commented
Documentation Update Needed for `deposit-security-module.md`:

The `maxDepositsPerBlock` and `minDepositBlockDistance` parameters have been relocated from the Deposit Security Module (DSM) to the Staking Router level. The documentation should be updated to reflect these changes.

- Remove or update the descriptions of maxDepositsPerBlock and minDepositBlockDistance from the DSM documentation.
- Eliminate references to any getters and setters, such as getMinDepositBlockDistance, which were removed as part of the Staking Router 1.5 (SR-1.5) scope updates.

2024-09-06 11:24 UTC, mkurayan commented
@vpetrenko The Sanity Checker documentation currently includes the description for oneOffCLBalanceDecreaseBPLimit and its related methods.
- Please update or remove the description for these items to align with the latest changes related to the negative rebase feature.

2024-09-06 11:44 UTC, mkurayan commented
Add to `node-operators-registry.md` description of 
- new `decreaseVettedSigningKeysCount` method
- `updateTargetValidatorsLimits`

2024-10-21 19:58 UTC, TheDZhon requested changes
Looks good!

The only concern here is the forced / boosted ambiguity.

2024-10-21 19:58 UTC, TheDZhon commented on docs/guides/oracle-spec/validator-exit-bus.md
> +2. Validator whose operator with the highest number of forced targeted validators to exit
```suggestion
2. Validator whose operator with the highest number of boosted targeted validators to exit
```

2024-10-21 19:58 UTC, TheDZhon commented on docs/guides/oracle-spec/validator-exit-bus.md
> +- target type (forced/soft) and target validators count
```suggestion
- target type (soft/boosted) and target validators count
```

2024-10-22 09:23 UTC, F4ever commented on docs/guides/oracle-spec/validator-exit-bus.md
> +5. Extend with forced to exit validators up to report limit or until there is no force requests.
```suggestion
5. Extend exit list with forced to exit validators (`targetLimitMode` is set to the boosted mode) up to the report limit or until there are no forced requests.
```

2024-10-22 14:41 UTC, TheDZhon approved these changes
GG

2024-10-23 09:33 UTC, rkolpakov approved these changes
LGTM

2024-10-25 16:26 UTC, merged