feat: data bus docs
lidofinance/docs pull request #443
Opened 2024-10-16 13:35 UTC by eddort

2024-10-17 12:41 UTC, infloop approved these changes

2024-10-18 11:55 UTC, F4ever approved these changes

2024-10-19 09:37 UTC, TheDZhon approved these changes
LGTM

2024-10-19 09:37 UTC, TheDZhon commented on docs/contracts/data-bus.md
> +- [DataBus on Polygon](https://polygonscan.com/address/0x37De961D6bb5865867aDd416be07189D2Dd960e6)
```suggestion
- [DataBus on Polygon PoS](https://polygonscan.com/address/0x37De961D6bb5865867aDd416be07189D2Dd960e6)
```

2024-10-19 09:38 UTC, TheDZhon requested changes

2024-10-19 09:38 UTC, TheDZhon commented on docs/contracts/data-bus.md
> +- [DataBus on Chaido](https://gnosis-chiado.blockscout.com/address/0x37De961D6bb5865867aDd416be07189D2Dd960e6)
```suggestion
- [DataBus on Chiado (Testnet)](https://gnosis-chiado.blockscout.com/address/0x37De961D6bb5865867aDd416be07189D2Dd960e6)
```

2024-10-20 18:33 UTC, TheDZhon approved these changes
:green_apple:

2024-10-21 09:00 UTC, merged