feat: SR + CSM contracts proposed -> actual
lidofinance/docs pull request #450
Opened 2024-10-18 14:06 UTC by dgusakov

DO NOT MERGE unless the vote is enacted

2024-10-19 16:40 UTC, avsetsin approved these changes
lgtm

2024-10-20 18:29 UTC, TheDZhon commented
:+1: 

One little concern: seems the CSM committee is missing here https://docs.lido.fi/multisigs/committees
cc: @lidofinance/lido-dao-ops-team

2024-10-21 06:50 UTC, dgusakov commented
CSM Multisig was added to the MS page

@TheDZhon FYI

2024-10-21 07:15 UTC, avsetsin approved these changes

2024-10-21 07:15 UTC, avsetsin commented on docs/multisigs/committees.md
> +**Aragon:** CSM was dded to the Lido on Ethereum protocol in [Omnibus vote #180 (items 20-26)](https://vote.lido.fi/vote/180)
```suggestion
**Aragon:** CSM was added to the Lido on Ethereum protocol in [Omnibus vote #180 (items 20-26)](https://vote.lido.fi/vote/180)
```

2024-10-21 09:00 UTC, TheDZhon approved these changes
LGTM

2024-10-22 08:37 UTC, TheDZhon requested changes

2024-10-22 08:37 UTC, TheDZhon commented on docs/deployed-contracts/index.md
I guess that the deployed `MinFirstAllocationStrategy` instance is missing :warning:

2024-10-22 08:57 UTC, avsetsin commented on docs/deployed-contracts/index.md
Fixed

2024-10-22 09:04 UTC, TheDZhon approved these changes
LGTM (what a bipolar man I am)

2024-10-22 14:43 UTC, kate-aleksseeva approved these changes
approved

2024-10-25 16:06 UTC, merged