Bridge guide
lidofinance/docs pull request #485
Opened 2024-12-07 13:23 UTC by iamnp

2024-12-08 17:50 UTC, arwer13 approved these changes

2024-12-09 12:35 UTC, TheDZhon requested changes
:+1: Thank you for updating the guide, I'd suggest to revise the meaning of the NEW→NEC update, bc:
1) NEW acted as a workgroup with only 'recommendation' sentiment
2) NEC has a formal assignment from the Lido DAO to recognize bridging endpoints

2024-12-09 12:35 UTC, TheDZhon commented on docs/token-guides/wsteth-bridging-guide.md
> +This guide provides recommendations provided by the [Network Expansion Committee (NEC)](https://snapshot.org/#/lido-snapshot.eth/proposal/0x7cdf1af7cfeb472ae202c45fb6d7e952bb34bfcbc82113549986b2bc2d5
NEC is a representative committee of the DAO, though with a limited scope :thinking: 

> This proposal aims to establish a Network Expansion Committee that will be assigned to formally recognize (w)stETH token bridging endpoints and denominations on new networks as canonical, acting on behalf of Lido DAO.

2024-12-09 15:18 UTC, TheDZhon approved these changes
LGTM

2024-12-09 15:18 UTC, merged